# Generated by Django 4.1.3 on 2022-12-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderposition_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('COOKING', 'Готовится'), ('DELIVERY', 'У курьера'), ('DONE', 'Готов')], default='CREATED', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
