# Generated by Django 4.1.3 on 2022-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('COOKING', 'Готовится'), ('DELIVERY', 'У курьера'), ('DONE', 'Готов')], db_index=True, default='CREATED', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
