# Generated by Django 4.1.3 on 2022-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Комментарий'),
        ),
    ]
