# Generated by Django 4.1.3 on 2022-12-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('OFFLINE', 'Наличными'), ('ONLINE', 'Электронно')], default='OFFLINE', max_length=50),
        ),
    ]
