# Generated by Django 4.1.3 on 2022-12-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closest_restaurant',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ближайший ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Первый звонок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('OFFLINE', 'Наличными'), ('ONLINE', 'Электронно')], default='OFFLINE', max_length=50, verbose_name='Способо оплаты'),
        ),
    ]
