# Generated by Django 4.1.3 on 2023-01-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='active_restaurant',
        ),
    ]
